set number
set laststatus=2
set list
set listchars=tab:>-,nbsp:_,trail:_,extends:_,precedes:_,eol:$
set hlsearch

set tabstop=2
set shiftwidth=2
set expandtab

syntax enable
colorscheme industry

highlight Normal ctermbg=none
highlight NonText ctermbg=none
highlight LineNr ctermbg=none
highlight Folded ctermbg=none
highlight EndOfBuffer ctermbg=none 
